name: first_workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: my-first-step
        run: echo "job1 first step text.txt" > text.txt | cat text.txt
